### ISSUE TITLE
Literal types and Types as values

### ISSUE THREAD

**Issue by BosqueLanguage** [BosqueLanguage/BosqueCore#85]
Want to support allowing constants in template types (and then of course converting these to values in code).

- [ ] Need to do syntax type(5) <-> value(T) kind of thing -- probably restrict to primitives and typedecls
- [ ] Need to implement in typechecker -- all works now that BSQON provides canonical values

**Comment by marron-at-work** [comment]
After some consideration this is not a priority feature.
